"""
ANSYS APDL Macro Generator for DRDO Shelter Thermal Simulation
==============================================================
Generates a complete .mac ANSYS Parametric Design Language script
that automates:
  1. Material property definition (density, conductivity, specific heat)
  2. 3D geometry creation (walls, roof, floor)
  3. Smart meshing (SMRTSIZE)
  4. Ladakh weather boundary conditions (convection, temperature loads)
  5. Transient thermal solve (ANTYPE, TRANS) over 24 hours
  6. Post-processing temperature contour plots

This file is NOT a replacement for ANSYS — it generates the automation
script that ANSYS Mechanical APDL can import and execute.
"""

from physics import MATERIALS, calculate_convection_coefficient


def _r_value_to_conductivity(r_value, thickness=0.20):
    """
    Convert R-value (m²K/W) to thermal conductivity k (W/m·K).
    k = thickness / R_value
    """
    if r_value <= 0:
        return 50.0  # Fallback for metals
    return thickness / r_value


def generate_ansys_macro(shelter_config: dict) -> str:
    """
    Generate a complete ANSYS APDL .mac macro script for transient thermal
    analysis of the shelter.

    Args:
        shelter_config: dict with keys:
            - wall_material, roof_material, window_material (str)
            - length, width, height (float, meters)
            - wall_thickness (float, meters, default 0.20)
            - roof_thickness (float, meters, default 0.15)
            - orientation (float, degrees, default 180)
            - occupants (int, default 5)
            - wind_speed_kmh (float, default 50)
            - outdoor_temp (float, °C, default -25)
            - floor_r_value (float, default 2.0)

    Returns:
        Complete APDL macro as a string
    """
    # Extract config with defaults
    wall_mat_name = shelter_config.get("wall_material", "Polyurethane Panel (PUF)")
    roof_mat_name = shelter_config.get("roof_material", "Polyurethane Panel (PUF)")
    window_mat_name = shelter_config.get("window_material", "Glass (Double Pane)")

    length = shelter_config.get("length", 6.0)
    width = shelter_config.get("width", 4.0)
    height = shelter_config.get("height", 2.5)
    wall_thick = shelter_config.get("wall_thickness", 0.20)
    roof_thick = shelter_config.get("roof_thickness", 0.15)
    orientation = shelter_config.get("orientation", 180.0)
    occupants = shelter_config.get("occupants", 5)
    wind_speed = shelter_config.get("wind_speed_kmh", 50.0)
    t_outside = shelter_config.get("outdoor_temp", -25.0)
    floor_r = shelter_config.get("floor_r_value", 2.0)

    # Material properties from physics.py
    wall_props = MATERIALS.get(wall_mat_name, MATERIALS["Polyurethane Panel (PUF)"])
    roof_props = MATERIALS.get(roof_mat_name, MATERIALS["Polyurethane Panel (PUF)"])
    window_props = MATERIALS.get(window_mat_name, MATERIALS["Glass (Double Pane)"])

    # Convert R-values to thermal conductivity
    wall_k = _r_value_to_conductivity(wall_props["r_value"], wall_thick)
    roof_k = _r_value_to_conductivity(roof_props["r_value"], roof_thick)
    window_k = _r_value_to_conductivity(window_props["r_value"], 0.01)

    # External convection coefficient
    h_ext = calculate_convection_coefficient(wind_speed)

    # Internal heat generation from occupants (W/m³)
    volume = length * width * height
    q_metabolic = (occupants * 175.0) / volume  # W/m³

    # Ground temperature (permafrost)
    t_ground = -15.0

    # Floor conductivity from R-value
    floor_thick = 0.10  # 10cm floor slab
    floor_k = floor_thick / floor_r if floor_r > 0 else 0.05

    # --- Build the APDL macro ---
    lines = []
    lines.append("! =====================================================================")
    lines.append("! DRDO SHELTER THERMAL SIMULATION — ANSYS APDL MACRO")
    lines.append("! Auto-generated by drdo-shelter-sim (Python Backend)")
    lines.append(f"! Shelter: {length}m × {width}m × {height}m")
    lines.append(f"! Wall Material: {wall_mat_name}")
    lines.append(f"! Roof Material: {roof_mat_name}")
    lines.append(f"! Window Material: {window_mat_name}")
    lines.append(f"! Orientation: {orientation}° (0=North, 180=South)")
    lines.append(f"! Outdoor Temp: {t_outside}°C  |  Wind: {wind_speed} km/h")
    lines.append(f"! h_ext (convection): {h_ext:.2f} W/m²K")
    lines.append("! =====================================================================")
    lines.append("")

    # --- Initialization ---
    lines.append("FINISH")
    lines.append("/CLEAR,START")
    lines.append("/TITLE,DRDO Tactical Shelter - Transient Thermal Analysis")
    lines.append(f"/UNITS,SI              ! SI units (meters, kg, seconds, °C)")
    lines.append("")

    # --- Preprocessor ---
    lines.append("! ====================== PREPROCESSOR ================================")
    lines.append("/PREP7")
    lines.append("")

    # Element type
    lines.append("! --- Element Type: 3D Thermal Solid ---")
    lines.append("ET,1,SOLID70           ! 8-node thermal brick element")
    lines.append("")

    # Material 1: Wall
    lines.append(f"! --- Material 1: Wall ({wall_mat_name}) ---")
    lines.append(f"MP,KXX,1,{wall_k:.6f}       ! Thermal conductivity (W/m·K)")
    lines.append(f"MP,DENS,1,{wall_props['density']:.1f}        ! Density (kg/m³)")
    lines.append(f"MP,C,1,{wall_props['specific_heat']:.1f}          ! Specific heat (J/kg·K)")
    lines.append("")

    # Material 2: Roof
    lines.append(f"! --- Material 2: Roof ({roof_mat_name}) ---")
    lines.append(f"MP,KXX,2,{roof_k:.6f}       ! Thermal conductivity (W/m·K)")
    lines.append(f"MP,DENS,2,{roof_props['density']:.1f}        ! Density (kg/m³)")
    lines.append(f"MP,C,2,{roof_props['specific_heat']:.1f}          ! Specific heat (J/kg·K)")
    lines.append("")

    # Material 3: Window
    lines.append(f"! --- Material 3: Window ({window_mat_name}) ---")
    lines.append(f"MP,KXX,3,{window_k:.6f}      ! Thermal conductivity (W/m·K)")
    lines.append(f"MP,DENS,3,{window_props['density']:.1f}       ! Density (kg/m³)")
    lines.append(f"MP,C,3,{window_props['specific_heat']:.1f}         ! Specific heat (J/kg·K)")
    lines.append("")

    # Material 4: Floor
    lines.append(f"! --- Material 4: Floor (Insulated Slab) ---")
    lines.append(f"MP,KXX,4,{floor_k:.6f}       ! Thermal conductivity (W/m·K)")
    lines.append(f"MP,DENS,4,2400.0              ! Density (concrete slab)")
    lines.append(f"MP,C,4,840.0                  ! Specific heat (concrete)")
    lines.append("")

    # --- Geometry ---
    lines.append("! ====================== GEOMETRY ====================================")
    lines.append("")

    # Outer wall envelope
    lines.append("! --- Outer Wall Envelope ---")
    lines.append(f"BLOCK,0,{length},{floor_thick},{floor_thick + height},0,{width}")
    lines.append("VATT,1,,1")
    lines.append("")

    # Inner void
    lines.append("! --- Inner Void ---")
    lines.append(f"BLOCK,{wall_thick},{length - wall_thick},{floor_thick},{floor_thick + height},{wall_thick},{width - wall_thick}")
    lines.append("")

    # Boolean subtraction for hollow envelope
    lines.append("! --- Boolean Volume Subtraction (VSBV) ---")
    lines.append("VSBV,1,2               ! Subtract inner void from outer envelope")
    lines.append("")

    # Floor slab
    lines.append("! --- Floor Slab ---")
    lines.append(f"BLOCK,0,{length},0,{floor_thick},0,{width}")
    lines.append("VATT,4,,1")
    lines.append("")

    # Roof
    lines.append("! --- Roof ---")
    lines.append(f"BLOCK,0,{length},{floor_thick + height},{floor_thick + height + roof_thick},0,{width}")
    lines.append("VATT,2,,1")
    lines.append("")

    # Window (simplified cutout logic is additive here due to shell logic, but APDL handles it with VGLUE)
    win_z_start = width / 2 - (width * 0.15)
    win_z_end = width / 2 + (width * 0.15)
    win_y_start = floor_thick + height * 0.3
    win_y_end = floor_thick + height * 0.7
    lines.append("! --- Window (Right Wall Cutout Placeholder) ---")
    lines.append(f"BLOCK,{length - wall_thick},{length},{win_y_start:.4f},{win_y_end:.4f},{win_z_start:.4f},{win_z_end:.4f}")
    lines.append("VATT,3,,1")
    lines.append("")

    # Boolean operations
    lines.append("! --- Glue all volumes together ---")
    lines.append("VGLUE,ALL")
    lines.append("")

    # --- Meshing ---
    lines.append("! ====================== MESHING =====================================")
    lines.append("SMRTSIZE,3             ! Smart sizing level 3 (medium-fine)")
    lines.append("MSHAPE,0,3D           ! Hex-dominant meshing")
    lines.append("MSHKEY,0              ! Free meshing")
    lines.append("VMESH,ALL             ! Mesh all volumes")
    lines.append("")

    # --- Boundary Conditions ---
    lines.append("! ====================== BOUNDARY CONDITIONS =========================")
    lines.append("")

    # External convection on all outer surfaces
    lines.append(f"! --- External Convection (Wind: {wind_speed} km/h) ---")
    lines.append("ASEL,S,EXT            ! Select all external areas")
    lines.append(f"SF,ALL,CONV,{h_ext:.2f},{t_outside:.1f}")
    lines.append("  ! Applied film coefficient = {:.2f} W/m²K".format(h_ext))
    lines.append("  ! Bulk temperature = {:.1f}°C".format(t_outside))
    lines.append("ALLSEL,ALL")
    lines.append("")

    # Ground boundary condition (bottom face)
    lines.append("! --- Ground/Permafrost (Bottom Face) ---")
    lines.append(f"ASEL,S,LOC,Y,0        ! Select bottom face (Y=0)")
    lines.append(f"SF,ALL,CONV,{1.0/floor_r:.4f},{t_ground:.1f}")
    lines.append("  ! Ground temperature = {:.1f}°C (Ladakh permafrost)".format(t_ground))
    lines.append("ALLSEL,ALL")
    lines.append("")

    # Internal heat generation (metabolic heat from occupants)
    lines.append(f"! --- Internal Heat Generation ({occupants} occupants × 175W) ---")
    lines.append("VSEL,S,MAT,,1         ! Select wall volumes (air cavity approximation)")
    lines.append(f"BFE,ALL,HGEN,,{q_metabolic:.4f}")
    lines.append("  ! Volumetric heat generation = {:.4f} W/m³".format(q_metabolic))
    lines.append("ALLSEL,ALL")
    lines.append("")

    # Initial temperature
    lines.append("! --- Initial Temperature ---")
    lines.append("ALLSEL,ALL")
    lines.append(f"IC,ALL,TEMP,{t_outside:.1f}        ! Initial temp = outdoor temp")
    lines.append("")

    lines.append("FINISH")
    lines.append("")

    # --- Solution ---
    lines.append("! ====================== SOLUTION ====================================")
    lines.append("/SOLU")
    lines.append("")
    lines.append("ANTYPE,TRANS           ! Transient thermal analysis")
    lines.append("TRNOPT,FULL            ! Full transient solution")
    lines.append("")
    lines.append("! --- Time Stepping (24-hour simulation) ---")
    lines.append("TIME,86400             ! End time = 86400 seconds (24 hours)")
    lines.append("DELTIM,300,60,3600     ! Time step: 300s default, 60s min, 3600s max")
    lines.append("KBC,1                  ! Stepped loading (discrete hourly BCs)")
    lines.append("")
    lines.append("OUTRES,ALL,ALL         ! Store all results at all substeps")
    lines.append("AUTOTS,ON              ! Auto time stepping")
    lines.append("")
    lines.append("SOLVE")
    lines.append("FINISH")
    lines.append("")

    # --- Post-Processing ---
    lines.append("! ====================== POST-PROCESSING =============================")
    lines.append("/POST1")
    lines.append("")
    lines.append("SET,LAST               ! Load last time step results")
    lines.append("PLNSOL,TEMP,,0         ! Plot temperature contour (nodal solution)")
    lines.append("")
    lines.append("! --- Temperature at shelter center ---")
    lines.append(f"*GET,T_CENTER,NODE,NODE({length/2:.2f},{floor_thick + height/2:.2f},{width/2:.2f}),TEMP")
    lines.append("*MSG,INFO,T_CENTER")
    lines.append("Shelter center temperature at t=24h: %G °C")
    lines.append("")
    lines.append("! --- Min/Max temperature ---")
    lines.append("NSORT,TEMP")
    lines.append("*GET,T_MIN,SORT,,MIN")
    lines.append("*GET,T_MAX,SORT,,MAX")
    lines.append("*MSG,INFO,T_MIN,T_MAX")
    lines.append("Temperature range: Min=%G °C  Max=%G °C")
    lines.append("")

    # --- Animated Results ---
    lines.append("! --- Animated Temperature Evolution ---")
    lines.append("/POST26")
    lines.append(f"NSOL,2,NODE({length/2:.2f},{floor_thick + height/2:.2f},{width/2:.2f}),TEMP")
    lines.append("PLVAR,2                ! Plot temperature vs time at center node")
    lines.append("")
    lines.append("FINISH")
    lines.append("! ====================== END OF MACRO ================================")
    lines.append(f"! Generated for: {wall_mat_name} walls | {roof_mat_name} roof")
    lines.append(f"! Orientation: {orientation}° | Occupants: {occupants}")
    lines.append("! =====================================================================")

    return "\n".join(lines)
