

def calculate_heat_transfer(t_inside, t_outside, area, r_value):
    """
    Calculates the heat loss (or gain) through a surface via conduction.
    Formula: Q = Area * ΔT / R-value
    Returns: Heat transfer in Watts (Joules/second)
    """
    if r_value <= 0:
        return 0
    return (t_inside - t_outside) * area / r_value

def calculate_solar_gain(solar_irradiance, window_area, absorptivity=0.7):
    """
    Calculates the heat gained from the sun entering the shelter.
    Formula: Q = Irradiance * Area * Absorptivity
    Returns: Heat gain in Watts
    """
    return solar_irradiance * window_area * absorptivity

def calculate_new_temperature(t_current, q_gain, q_loss, mass, specific_heat, dt_seconds=3600):
    """
    Calculates the new internal temperature after 1 hour (3600 seconds).
    Formula: ΔT = (Net Heat * Time) / (Mass * Specific Heat)
    Returns: New temperature in °C
    """
    # Net heat in Watts (Joules/second)
    q_net = q_gain - q_loss 
    
    # Total energy transferred over the time period (dt_seconds)
    total_energy_joules = q_net * dt_seconds
    
    # Thermal capacity of the shelter
    thermal_mass = mass * specific_heat
    
    if thermal_mass == 0:
        return t_current
        
    delta_t = total_energy_joules / thermal_mass
    return t_current + delta_t


def calculate_external_surface_temp(t_inside, t_outside, r_value, h_ext=25):
    """
    Estimates the external surface temperature of the wall for IR stealth.
    Formula derived from steady-state heat flux: q = h * (T_surf - T_out)
    h_ext = Convective heat transfer coefficient of winter wind (approx 25 W/m²K)
    """
    if r_value <= 0:
        return t_outside
    
    # Calculate how warm the outside of the wall gets due to escaping heat
    t_surf = t_outside + (t_inside - t_outside) / (r_value * h_ext)
    return t_surf

# --- Material Database ---
# Values: [R-Value (m²K/W), Density (kg/m³), Specific Heat (J/kg·K), Cost (INR/kg)]
MATERIALS = {
    "Concrete": {"r_value": 0.20, "density": 2400, "specific_heat": 840, "cost_per_kg": 5},
    "Brick": {"r_value": 0.30, "density": 1900, "specific_heat": 840, "cost_per_kg": 4},
    "Wood": {"r_value": 1.00, "density": 600, "specific_heat": 1200, "cost_per_kg": 40},
    "Polyurethane Panel (PUF)": {"r_value": 5.00, "density": 50, "specific_heat": 1400, "cost_per_kg": 250},
    "Glass (Single Pane)": {"r_value": 0.15, "density": 2500, "specific_heat": 750, "cost_per_kg": 60},
}


def calculate_metabolic_heat(occupants, watts_per_person=100):
    """
    Calculates the internal heat generated by human bodies.
    Formula: Q = Number of people * Watts per person
    """
    return occupants * watts_per_person

def calculate_ventilation_loss(t_inside, t_outside, volume, ach):
    """
    Calculates heat loss due to air exchange (ventilation).
    ACH = Air Changes per Hour
    Formula: Q = (ACH * Volume / 3600) * Air_Density * Air_Specific_Heat * ΔT
    """
    if t_inside <= t_outside:
        return 0
        
    # Standard values for high altitude (Ladakh ~4500m)
    air_density = 0.77  # kg/m^3 (thinner air at high altitude)
    air_specific_heat = 1005  # J/kg·K
    
    # Calculate cubic meters of air moved per second
    volume_per_second = (ach * volume) / 3600
    
    # Calculate heat lost to warming up the cold incoming air
    return volume_per_second * air_density * air_specific_heat * (t_inside - t_outside)